version: "3.8"

services:
  web:
    build: .
    container_name: fmp_docker_web
    volumes:
      - ./src:/var/www/html:delegated
    expose:
      - "80"
    networks:
      - fmp_network
    depends_on:
      db:
        condition: service_healthy

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: fmp_docker_node
    working_dir: /app
    volumes:
      - ./src:/app:delegated
    expose:
      - "3000"
    networks:
      - fmp_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: fmp_docker_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: children_db
    ports:
      - "3307:3306"
    volumes:
      - ./src/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql_data:/var/lib/mysql
    networks:
      - fmp_network
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -u root -e 'SELECT 1'" ]
      interval: 15s
      timeout: 10s
      retries: 15

  nginx:
    image: nginx:latest
    container_name: fmp_docker_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"  # This can remain if you're testing SSL locally
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - fmp_network

networks:
  fmp_network:
    driver: bridge

volumes:
  mysql_data:
